import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    home: 'Offers',
    shop: 'Shop',
    help: 'Help',
    addToCart: 'Add to Cart',
    addedToCart: 'Added to cart',
    cart: 'Cart',
    checkout: 'Checkout',
    endsIn: 'Ends in',
    shopAll: 'Discover More',
    specifications: 'Specifications',
    keyBenefits: 'Key Benefits',
    color: 'Color',
    size: 'Size',
    material: 'Material',
    weight: 'Weight',
    style: 'Style',
    bestSeller: 'Best Seller',
    saleEnded: 'Sale Ended',
    emptyCart: 'Your cart is empty.',
    subtotal: 'Subtotal',
    tax: 'Tax',
    total: 'Total',
    loading: 'Loading...',
    searchPlaceholder: 'Search products by name or description...',
    currency: 'EGP',
    all: 'All',
    noProducts: 'No products found in this category.',
    'Home Fragrance': 'Home Fragrance',
    'Cleaning': 'Cleaning',
    'Smart Home': 'Smart Home',
    'Bath & Skin': 'Bath & Skin',
    'Baby Care': 'Baby Care',
    'Baby Essentials': 'Baby Essentials',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    contactUs: 'Contact Us',
    aboutUs: 'About Us',
    newsletter: 'Newsletter',
    newsletterDesc: 'Subscribe to get special offers, free giveaways, and once-in-a-lifetime deals.',
    enterEmail: 'Enter your email',
    subscribe: 'Subscribe',
    support: 'Support',
    legal: 'Legal',
    madeForMoms: 'Made for moms, by moms.',
    categories: 'Categories',
    dashboard: 'Dashboard',
    orders: 'Orders',
    users: 'Users',
    products: 'Products',
    settings: 'Settings',
    totalRevenue: 'Total Revenue',
    averageOrderValue: 'Average Order Value',
    activeOrders: 'Active Orders',
    totalCustomers: 'Total Customers',
    recentOrders: 'Recent Orders',
    viewAll: 'View All',
    storeCategories: 'Store Categories',
    deleteCategory: 'Delete Category',
    promoCodes: 'Promo Codes',
    influencers: 'Influencers',
    categoryManagement: 'Category Management',
    locationsShipping: 'Locations & Shipping',
    productOptions: 'Product Options',
    globalReviews: 'Global Reviews',
    addCategory: 'Add Category',
    newMainCategoryName: 'New Main Category Name...',
    subCategories: 'Sub-Categories',
    saveChanges: 'Save Changes',
    icon: 'Icon',
    categoryManagementDesc: 'Add, edit, and delete the categories available in your store',
    'Electronics': 'Electronics',
    'Smartphones': 'Smartphones',
    'Laptops': 'Laptops',
    'Accessories': 'Accessories',
    'Clothing': 'Clothing',
    'Men': 'Men',
    'Women': 'Women',
    'Kids': 'Kids',
    'Home & Kitchen': 'Home & Kitchen',
    'Furniture': 'Furniture',
    'Decor': 'Decor',
    'Appliances': 'Appliances',
    'Health & Beauty': 'Health & Beauty',
    'Skincare': 'Skincare',
    'Makeup': 'Makeup',
    'Personal Care': 'Personal Care',
    orderId: 'Order ID',
    customer: 'Customer',
    status: 'Status',
    date: 'Date',
    allItem: 'All item',
    cartTotals: 'Cart Totals',
    shipping: 'Shipping',
    totalAmount: 'Total Amount',
    summary: 'Summary',
    shippingAddress: 'Shipping Address',
    paymentMethod: 'Payment Method',
    pending: 'Pending',
    shipped: 'Shipped',
    delivered: 'Delivered',
    cancelled: 'Cancelled',
    deliveryDetails: 'Delivery Details',
    firstName: 'First Name',
    lastName: 'Last Name',
    mobileNumber: 'Mobile Number',
    governorate: 'Governorate',
    district: 'District',
    streetAddress: 'Street Address',
    searchGovernorate: 'Governorate...',
    searchDistrict: 'District...',
    orderDetail: 'Order Detail',
    productName: 'Product Name',
    quantity: 'Quantity',
    price: 'Price',
    copyForDriver: 'Copy for Driver',
    building: 'Building',
    apartment: 'Apartment',
    remove: 'Remove',
    continueShopping: 'Continue Shopping',
    secureCheckout: 'Secure Checkout',
    havePromoCode: 'Have a promo code?',
    apply: 'Apply',
    buildingOptional: 'Building Number / Name',
    apartmentOptional: 'Apartment / Floor (Optional)',
    cashOnDelivery: 'Cash on Delivery (COD)',
    completeOrder: 'Complete Order',
    customerReviews: 'What Our Customers Say',
    termsAgreement: 'By placing your order, you agree to our Terms of Service',
    orderConfirmed: 'Order Confirmed!',
    thankYouPurchase: 'Thank you for your purchase. Your order #{orderId} has been successfully placed.',
    emailConfirmationShort: 'We will contact you shortly via phone or message to confirm your order details.',
    'Flash Sale': 'Flash Sale',
    'Curated Picks': 'Curated Picks',
    'More Home Essentials': 'More Home Essentials',
    secs: 'SECS',
    mins: 'MINS',
    hours: 'HOURS',
    off: 'OFF',
    outOfStock: 'Out of Stock',
    inventory: 'Inventory',
    errorLoadingProduct: 'Error Loading Product',
    tryAgain: 'Try Again',
    productNotFound: 'Product Not Found',
    backToShop: 'Back to Shop',
    partnerPortal: 'Partner Portal',
    totalUses: 'Total Uses',
    salesGenerated: 'Sales Generated',
    totalCommissionEarned: 'Total Commission Earned',
    inventoryVisibility: 'Inventory & Visibility',
    collectionsFlashSale: 'Collections & Flash Sale',
    collectionBuilderDesc: 'Build your storefront sections. Add products, reorder them, and set custom flash sale prices.',
    saveAllChanges: 'Save All Changes',
    collectionNamePlaceholder: 'Collection Name',
    saleEndDate: 'Sale End Date',
    saleStartDate: 'Sale Start Date',
    maxDisplayedItems: 'Max Displayed Items',
    addProduct: 'Add Product +',
    productsInCollection: 'Products in Collection ({count} / {max})',
    noProductsInCollection: 'No products in this collection.',
    addProducts: 'Add Products',
    addNewCollection: 'Add New Collection +',
    save: 'Save',
    cancel: 'Cancel',
    removeFromCollection: 'Remove from collection',
    noDiscount: 'No discount',
    shippingConfig: 'Shipping Config',
    active: 'Active',
    inactive: 'Inactive',
    flatRateShippingCost: 'Flat Rate Shipping Cost (EGP):',
    addGovernorate: 'Add Governorate',
    governorateEn: 'Governorate (EN)',
    governorateAr: 'المحافظة (AR)',
    districts: 'Districts',
    districtEn: 'District (EN)',
    districtAr: 'المنطقة (AR)',
    addDistrict: 'Add District'
  },
  ar: {
    home: 'عروض',
    shop: 'التسوق',
    help: 'المساعدة',
    addToCart: 'أضف للسلة',
    addedToCart: 'تمت الإضافة',
    cart: 'السلة',
    checkout: 'إتمام الطلب',
    endsIn: 'ينتهي في',
    shopAll: 'اكتشف المزيد',
    specifications: 'المواصفات',
    keyBenefits: 'المميزات الرئيسية',
    color: 'اللون',
    size: 'المقاس',
    material: 'الخامة',
    weight: 'الوزن',
    style: 'الستايل',
    bestSeller: 'الأكثر مبيعاً',
    saleEnded: 'انتهى العرض',
    emptyCart: 'السلة فاضية.',
    subtotal: 'المجموع الفرعي',
    tax: 'الضريبة',
    total: 'الإجمالي',
    loading: 'جاري التحميل...',
    searchPlaceholder: 'دور على منتج بالاسم أو الوصف...',
    currency: 'جنيه',
    all: 'الكل',
    noProducts: 'مفيش منتجات في القسم ده.',
    'Home Fragrance': 'معطرات المنزل',
    'Cleaning': 'المنظفات',
    'Smart Home': 'المنزل الذكي',
    'Bath & Skin': 'العناية بالبشرة والاستحمام',
    'Baby Care': 'عناية الأطفال',
    'Baby Essentials': 'أساسيات الأطفال',
    'Electronics': 'إلكترونيات',
    'Smartphones': 'هواتف ذكية',
    'Laptops': 'لابتوبات',
    'Accessories': 'إكسسوارات',
    'Clothing': 'ملابس',
    'Men': 'رجال',
    'Women': 'نساء',
    'Kids': 'أطفال',
    'Home & Kitchen': 'المنزل والمطبخ',
    'Furniture': 'أثاث',
    'Decor': 'ديكور',
    'Appliances': 'أجهزة منزلية',
    'Health & Beauty': 'الصحة والجمال',
    'Skincare': 'عناية بالبشرة',
    'Makeup': 'مكياج',
    'Personal Care': 'عناية شخصية',
    'Trending': 'شائع',
    'New Arrival': 'وصل حديثاً',
    'Limited Stock': 'كمية محدودة',
    'Top Rated': 'الأعلى تقييماً',
    'Staff Pick': 'اختيار الموظفين',
    privacyPolicy: 'سياسة الخصوصية',
    termsOfService: 'شروط الخدمة',
    contactUs: 'تواصل معنا',
    aboutUs: 'عننا',
    newsletter: 'النشرة البريدية',
    newsletterDesc: 'اشترك عشان يوصلك عروضنا وخصوماتنا الحصرية.',
    enterEmail: 'اكتب إيميلك',
    subscribe: 'اشتراك',
    support: 'الدعم',
    legal: 'قانوني',
    madeForMoms: 'من الأمهات، للأمهات.',
    categories: 'الأقسام',
    dashboard: 'لوحة التحكم',
    orders: 'الطلبات',
    users: 'العملاء',
    products: 'المنتجات',
    settings: 'الإعدادات',
    totalRevenue: 'إجمالي المبيعات',
    averageOrderValue: 'متوسط الطلب',
    activeOrders: 'الطلبات الحالية',
    totalCustomers: 'إجمالي العملاء',
    recentOrders: 'أحدث الطلبات',
    viewAll: 'عرض الكل',
    orderId: 'رقم الطلب',
    customer: 'العميل',
    status: 'الحالة',
    date: 'التاريخ',
    allItem: 'كل العناصر',
    cartTotals: 'إجمالي السلة',
    shipping: 'الشحن',
    totalAmount: 'الإجمالي النهائي',
    summary: 'الملخص',
    shippingAddress: 'عنوان الشحن',
    paymentMethod: 'طريقة الدفع',
    pending: 'قيد الانتظار',
    shipped: 'تم الشحن',
    delivered: 'تم التوصيل',
    cancelled: 'ملغاة',
    deliveryDetails: 'تفاصيل التوصيل',
    firstName: 'الاسم الأول',
    lastName: 'الاسم الأخير',
    mobileNumber: 'رقم الموبايل',
    governorate: 'المحافظة',
    district: 'المنطقة',
    streetAddress: 'عنوان الشارع',
    searchGovernorate: 'المحافظة...',
    searchDistrict: 'المنطقة...',
    orderDetail: 'تفاصيل الطلب',
    productName: 'اسم المنتج',
    quantity: 'الكمية',
    price: 'السعر',
    copyForDriver: 'نسخ للمندوب',
    building: 'العمارة',
    apartment: 'الشقة',
    remove: 'حذف',
    continueShopping: 'متابعة التسوق',
    secureCheckout: 'الدفع الآمن',
    havePromoCode: 'عندك كود خصم؟',
    apply: 'تطبيق',
    buildingOptional: 'رقم المبنى / اسم العمارة',
    apartmentOptional: 'رقم الشقة / الدور (اختياري)',
    cashOnDelivery: 'الدفع عند الاستلام',
    completeOrder: 'إتمام الطلب',
    customerReviews: 'رأي عملائنا',
    termsAgreement: 'بإتمامك للطلب، أنت توافق على شروط الخدمة الخاصة بنا',
    orderConfirmed: 'تم تأكيد الطلب!',
    thankYouPurchase: 'شكراً لشرائك. تم تسجيل طلبك رقم #{orderId} بنجاح.',
    emailConfirmationShort: 'هنتواصل معاك قريب عن طريق التليفون أو رسالة عشان نأكد تفاصيل الطلب.',
    'Flash Sale': 'عروض حصرية',
    'Curated Picks': 'مختارات مميزة',
    'More Home Essentials': 'المزيد من مستلزمات المنزل',
    secs: 'ثانية',
    mins: 'دقيقة',
    hours: 'ساعة',
    off: 'خصم',
    outOfStock: 'نفدت الكمية',
    inventory: 'المخزون',
    errorLoadingProduct: 'خطأ في تحميل المنتج',
    tryAgain: 'حاول مرة أخرى',
    productNotFound: 'المنتج غير موجود',
    backToShop: 'العودة للمتجر',
    partnerPortal: 'بوابة الشركاء',
    totalUses: 'إجمالي الاستخدامات',
    salesGenerated: 'المبيعات الناتجة',
    totalCommissionEarned: 'إجمالي العمولة المكتسبة',
    inventoryVisibility: 'المخزون والظهور',
    deleteCategory: 'حذف القسم',
    promoCodes: 'أكواد الخصم',
    influencers: 'المؤثرين',
    categoryManagement: 'إدارة الأقسام',
    locationsShipping: 'المناطق والشحن',
    productOptions: 'خيارات المنتجات',
    globalReviews: 'التقييمات العامة',
    addCategory: 'إضافة قسم',
    newMainCategoryName: 'اسم القسم الرئيسي...',
    subCategories: 'الأقسام الفرعية',
    saveChanges: 'حفظ التغييرات',
    icon: 'الأيقونة',
    categoryManagementDesc: 'إضافة، تعديل، وحذف الأقسام المتاحة في متجرك',
    'Electronics': 'الإلكترونيات',
    'Smartphones': 'الهواتف الذكية',
    'Laptops': 'الحواسيب المحمولة',
    'Accessories': 'الإكسسوارات',
    'Clothing': 'الملابس',
    'Men': 'رجالي',
    'Women': 'حريمي',
    'Kids': 'أطفال',
    'Home & Kitchen': 'المنزل والمطبخ',
    'Furniture': 'الأثاث',
    'Decor': 'الديكور',
    'Appliances': 'الأجهزة المنزلية',
    'Health & Beauty': 'الصحة والجمال',
    'Skincare': 'العناية بالبشرة',
    'Makeup': 'المكياج',
    'Personal Care': 'العناية الشخصية',
    'Beauty': 'الجمال',
    'Fashion': 'الأزياء',
    'Baby Essentials': 'مستلزمات الأطفال',
    'Baby Care': 'رعاية الأطفال',
    'Bath & Skin': 'الاستحمام والبشرة',
    'Diapers': 'الحفاضات',
    collectionBuilder: 'منشئ المجموعات',
    selectProductsToAdd: 'اختر المنتجات للإضافة',
    collectionsFlashSale: 'أقسام المتجر والعروض',
    collectionBuilderDesc: 'نظم شكل متجرك هنا. أضف المنتجات ورتبها براحتك، وتقدر تحدد أسعار العروض بسهولة.',
    saveAllChanges: 'حفظ كل التغييرات',
    collectionNamePlaceholder: 'اسم القسم أو المجموعة',
    saleEndDate: 'تاريخ انتهاء العرض',
    saleStartDate: 'تاريخ بداية العرض',
    maxDisplayedItems: 'أقصى عدد منتجات يظهر',
    addProduct: 'إضافة منتج +',
    productsInCollection: 'المنتجات في القسم ({count} / {max})',
    noProductsInCollection: 'مفيش منتجات في القسم ده.',
    addProducts: 'إضافة منتجات',
    addNewCollection: 'إضافة قسم جديد +',
    save: 'حفظ',
    cancel: 'إلغاء',
    removeFromCollection: 'إزالة من القسم',
    noDiscount: 'بدون خصم',
    shippingConfig: 'إعدادات الشحن',
    active: 'مفعل',
    inactive: 'معطل',
    flatRateShippingCost: 'تكلفة الشحن الثابتة (جنيه):',
    addGovernorate: 'إضافة محافظة',
    governorateEn: 'المحافظة (EN)',
    governorateAr: 'المحافظة (AR)',
    districts: 'المناطق',
    districtEn: 'المنطقة (EN)',
    districtAr: 'المنطقة (AR)',
    addDistrict: 'إضافة منطقة'
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  useEffect(() => {
    const savedLang = localStorage.getItem('storeLanguage');
    if (savedLang && (savedLang === 'en' || savedLang === 'ar')) {
      setLanguage(savedLang);
    }
  }, []);

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    localStorage.setItem('storeLanguage', language);
  }, [language]);

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'ar' : 'en');
  };

  const t = (key) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
